security:
    firewalls:
        login:
          pattern: ^/secured/login$
          security: false
          
        secured_area:
          pattern: ^/secured/
          form_login:
            check_path: /secured/login_check
            login_path: /secured/login
            failure_path:                   null
            always_use_default_target_path: false
            default_target_path:            /secured/
            target_path_parameter:          test
            use_referer:                    false 
          logout:
            path:   /secured/logout
            target: /
#            pattern:    ^/
#            anonymous: ~
#            form_login:
#                login_path:  /login
#                check_path:  /login_check

    access_control:
        - { path: ^/secured, roles: ROLE_USER }

    providers:
        in_memory:
            users:
                user:  { password: userpass, roles: 'ROLE_USER' }
                admin: { password: adminpass, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        