homepage:
    pattern:  /
    defaults: { _controller: AcmeLoginBundle:Default:index }

admin:
  pattern: /admin/
  defaults: { _controller: AcmeLoginBundle:Admin:index }
  
login:
    pattern:   /login
    defaults:  { _controller: AcmeSecurityBundle:Security:login }
login_check:
    pattern:   /login_check